### ISSUE TITLE
Verifying release RPMs is not possible

### ISSUE THREAD

**Issue by JeffreyVdb** [k3s-io/k3s-selinux#17]
I am trying to create a CI pipeline that downloads a certain RPM version from releases.
There doesn't seem to be a way to verify the downloaded RPM. From the `drone.yml` file I can see that there is a signing process for the RPM packages, but a public key isn't mentioned anywhere.

There is a checksum file available for every release, but we cannot verify whether these hashes are generated by a trusted instance. For this we would need a signed signature file as well.

Perhaps I'm missing something.

**Comment by Oats87** [comment]
Jeffrey,

Sorry for the late response on this. The public key for the signed RPMs is at https://rpm.rancher.io/public.key

**Comment by dweomer** [comment]
Fixed via https://github.com/k3s-io/k3s-selinux/commit/e4307b98dd1e4c1d9a1cdb09af8b48ad1e91f8f5
