### ISSUE TITLE
k3s-selinux support for SLE Micro and openSUSE MicroOS

### ISSUE THREAD

**Issue by sysrich** [k3s-io/k3s-selinux#19]
Related to #8 but different, as both SLE Micro and openSUSE MicroOS have both `container-selinux` and `selinux-policy-targeted` packages

Both distributions would like to enable SELinux by default, but installing k3s is a common use case by those users and customers already, and are currently hindered by the lack of a k3s-selinux package. 

Please can SLE Micro (based on SLE 15 SP2) and openSUSE MicroOS (based on openSUSE Tumbleweed) k3s-selinux packages be brewed, with the above dependencies?

Once that exists changes to install.sh will be needed to use more appropriate commands than `yum install`, but meanwhile https://github.com/k3s-io/k3s/pull/3088 has been submitted to stop SUSE/openSUSE users trying to make things worse with the current error messages.

**Comment by johanneskastl** [comment]
Sorry for abusing this issue, but I started to build a package for this in the openSUSE Build Service:
https://build.opensuse.org/package/show/home:ojkastl_buildservice:Branch_devel_kubic/k3s-selinux

I noticed that the k3s.if file is empty in the latest stable release v0.5.latest.1, so I added the latest one from commit 7b982cf

@sysrich SR to devel:kubic is [here](https://build.opensuse.org/request/show/945135).
