### ISSUE TITLE
k3s-selinux rpm for CentOS 9

### ISSUE THREAD

**Issue by pandemir** [k3s-io/k3s-selinux#31]
Hello, is it possible to make a package for CentOS 9?

**Comment by loganmc10** [comment]
The el8 RPM works on Fedora 36, so I assume it also works on CentOS 9 (which is forked from Fedora 34)

**Comment by pandemir** [comment]
> The el8 RPM works on Fedora 36, so I assume it also works on CentOS 9 (which is forked from Fedora 34)

It really works, thank you!

**Comment by pandemir** [comment]
The el8 RPM works on el9
